"""empty message

Revision ID: 12b547213bc4
Revises: 548c2526258c
Create Date: 2021-07-14 11:32:46.524116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b547213bc4'
down_revision = '548c2526258c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_shop_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_buyer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'buyers', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('orders_products_product_id_fkey', 'orders_products', type_='foreignkey')
    op.drop_constraint('orders_products_order_id_fkey', 'orders_products', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('prices_pt_id_fkey', 'prices', type_='foreignkey')
    op.drop_constraint('prices_product_id_fkey', 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'prices_type', ['pt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prices', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shops_buyer_id_fkey', 'shops', type_='foreignkey')
    op.drop_constraint('shops_pt_id_fkey', 'shops', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'buyers', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shops', 'prices_type', ['pt_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.create_foreign_key('shops_pt_id_fkey', 'shops', 'prices_type', ['pt_id'], ['id'])
    op.create_foreign_key('shops_buyer_id_fkey', 'shops', 'buyers', ['buyer_id'], ['id'])
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key('prices_product_id_fkey', 'prices', 'products', ['product_id'], ['id'])
    op.create_foreign_key('prices_pt_id_fkey', 'prices', 'prices_type', ['pt_id'], ['id'])
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.drop_constraint(None, 'orders_products', type_='foreignkey')
    op.create_foreign_key('orders_products_order_id_fkey', 'orders_products', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('orders_products_product_id_fkey', 'orders_products', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_buyer_id_fkey', 'orders', 'buyers', ['buyer_id'], ['id'])
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key('orders_shop_id_fkey', 'orders', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###
