"""empty message

Revision ID: 408bc8bfcbdb
Revises: 8122a347d7c3
Create Date: 2021-06-19 10:59:34.376757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408bc8bfcbdb'
down_revision = '8122a347d7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shops_kode_key', 'shops', type_='unique')
    op.create_unique_constraint(None, 'shops', ['buyer_id', 'kode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='unique')
    op.create_unique_constraint('shops_kode_key', 'shops', ['kode'])
    # ### end Alembic commands ###
