"""empty message

Revision ID: 8122a347d7c3
Revises: a80f2b8f358e
Create Date: 2021-06-18 18:25:11.843843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8122a347d7c3'
down_revision = 'a80f2b8f358e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buyers_pt_id_fkey', 'buyers', type_='foreignkey')
    op.drop_column('buyers', 'pt_id')
    op.add_column('shops', sa.Column('pt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'prices_type', ['pt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'pt_id')
    op.add_column('buyers', sa.Column('pt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('buyers_pt_id_fkey', 'buyers', 'prices_type', ['pt_id'], ['id'])
    # ### end Alembic commands ###
