"""empty message

Revision ID: a80f2b8f358e
Revises: da120f0ab991
Create Date: 2021-06-18 18:14:40.317989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80f2b8f358e'
down_revision = 'da120f0ab991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_bayer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'buyers', ['buyer_id'], ['id'])
    op.drop_column('orders', 'bayer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('bayer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_bayer_id_fkey', 'orders', 'buyers', ['bayer_id'], ['id'])
    op.drop_column('orders', 'buyer_id')
    # ### end Alembic commands ###
