"""empty message

Revision ID: e53bd71cdc20
Revises: 1b4c5f26281d
Create Date: 2021-06-15 18:23:38.969706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53bd71cdc20'
down_revision = '1b4c5f26281d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['pt_id'], ['prices_type.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'pt_id', 'date', name='price_pk')
    )
    op.create_index(op.f('ix_prices_date'), 'prices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_date'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
