"""empty message

Revision ID: 2b5947666330
Revises: bc746ea8e046
Create Date: 2021-07-25 13:37:16.498785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5947666330'
down_revision = 'bc746ea8e046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('price_pk', 'prices', ['product_id', 'pt_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_pk', 'prices', type_='unique')
    op.drop_column('prices', 'id')
    # ### end Alembic commands ###
